### ISSUE TITLE
Time for TA meeting

### ISSUE THREAD

**Issue by Sad-0w** [Sad-0w/SPC_final_project#5]
What time is everyone available to meet with the TA for everyone

**Comment by Sad-0w** [comment]
Monday/Friday are the days for Chinmay and I

**Comment by chinmayL27** [comment]
can we do Monday from 2 to 2:30 for this week as we missed last week's Friday?

**Comment by chinmayL27** [comment]
Also, we can close the issue if everyone is okay with Friday 2:30 to 3.

**Comment by dawnbreaker28** [comment]
I'm fine with Friday 2:30 to 3
